consumable screens added
SettleMintIndia/uk_shasan pull request #7
Opened 2022-05-05 11:58 UTC by PrashanthReddyPR

2022-05-05 13:16 UTC, Gorantasathish requested changes

2022-05-05 13:16 UTC, Gorantasathish commented on yarn.lock
> +<<<<<<< Updated upstream
@PrashanthReddyPR  why you pushed this lock file and it has conflicts

2022-05-05 13:16 UTC, Gorantasathish commented on src/components/Sidebar/index.js
> +    /* if( user_role == 'Admin'){
@PrashanthReddyPR  why you commented this lines?

2022-05-05 13:16 UTC, Gorantasathish commented on src/components/FixedRequest/index.js
> +           // setApproval(result);
hope we can remove this commented lines right @PrashanthReddyPR

2022-05-05 13:16 UTC, Gorantasathish commented on src/components/CentralConsumableAssetIssue/index.js
> +        /*   let vendorList = await API_Auth.getVendors();
remove commented code if not required

2022-05-05 13:16 UTC, Gorantasathish commented on src/API_Auth.js
> +          let url = UPDATE_ITEM_TO_ASSET_API_URL+"assetID="+assetID */
is it merged corred?

2022-05-06 05:12 UTC, PrashanthReddyPR commented on src/components/Sidebar/index.js
> +    /* if( user_role == 'Admin'){
i didnt do any changes in this file

2022-05-06 05:12 UTC, PrashanthReddyPR commented on src/components/FixedRequest/index.js
> +           // setApproval(result);
yes ill remove

2022-05-06 05:12 UTC, PrashanthReddyPR commented on src/components/CentralConsumableAssetIssue/index.js
> +        /*   let vendorList = await API_Auth.getVendors();
ok

2022-05-06 05:22 UTC, PrashanthReddyPR commented on src/API_Auth.js
> +          let url = UPDATE_ITEM_TO_ASSET_API_URL+"assetID="+assetID */
i didnt get this

2022-05-06 05:23 UTC, PrashanthReddyPR commented on src/API_Auth.js
> +          let url = UPDATE_ITEM_TO_ASSET_API_URL+"assetID="+assetID */
i didnt understand this

2022-05-06 06:08 UTC, Gorantasathish commented on src/components/Sidebar/index.js
> +    /* if( user_role == 'Admin'){
yeah you missed something while resolving conflicts

2022-05-06 06:59 UTC, Gorantasathish approved these changes

2022-05-06 07:00 UTC, merged